# Generated by Django 3.0.3 on 2020-02-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cls', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('score', models.FloatField()),
            ],
        ),
    ]
